apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs_app
  template:
    metadata:
      labels:
        app: nodejs_app
    spec:
      containers:
      - name: nodejs_app
        image: abhimanyusingh18/nodejs_app:latest
        ports:
        - containerPort: 3000
